### ISSUE TITLE
ModuleNotFoundError: No module named 'typing_extensions'

### ISSUE THREAD

**Issue by dchimeno** [Yelp/swagger_spec_validator#161]
**typing_extensions** is imported here: https://github.com/Yelp/swagger_spec_validator/blob/master/swagger_spec_validator/common.py#L18 but as fas as I know is not installed along this package.

Tests are not failing because typing_extensions is installed in dev requirements.

This happens since > 3.0

**Comment by googlygoo** [comment]
Just adding to this issue, here is an example of reproducing the issue.

```
➜  python -m venv .venv
➜  . ./.venv/bin/activate
➜  pip install swagger-spec-validator
➜  python
Python 3.9.13 (main, Jul  7 2022, 09:29:37)
[Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from swagger_spec_validator.common import SwaggerValidationError
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/.venv/lib/python3.9/site-packages/swagger_spec_validator/__init__.py", line 1, in <module>
    from swagger_spec_validator.common import SwaggerValidationError
  File "~/.venv/lib/python3.9/site-packages/swagger_spec_validator/common.py", line 18, in <module>
    from typing_extensions import ParamSpec
ModuleNotFoundError: No module named 'typing_extensions'
```
